name: Java CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B package
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Test with Maven
        run: mvn -B test
  lint-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: |
          npm i @commitlint/{config-angular,cli} -D
          npx commitlint -x "@commitlint/config-angular" --from=origin/master --to=HEAD
  comment:
    runs-on: ubuntu-latest
    needs: [build, test, lint-commit]
    if: failure()
    steps:
      - uses: actions/github-script@0.2.0
        with:
          github-token: ${{github.token}}
          script: |
            github.issues.createComment({...context.issue, body: '💥 failed :<'})
